spring:
  h2:
    console:
      enabled: true
      path: /books-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:books
    username: exampleuser
    password: examplepasswort
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect